In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [19]:
import sys 
import pandas as pd
import numpy as np


import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib import style
%matplotlib inline

In [ ]:
sys.path.insert(1, '/content/drive/MyDrive/tabular_project')
!unzip '/content/drive/MyDrive/tabular_project/Pima Indians Diabetes Database.zip' -d '/content/Pima-Indians-Diabetes-Database'

Archive:  /content/drive/MyDrive/tabular_project/Pima Indians Diabetes Database.zip
  inflating: /content/Pima-Indians-Diabetes-Database/Pima Indians Diabetes Database.csv
  inflating: /content/Pima-Indians-Diabetes-Database/__MACOSX/._Pima Indians Diabetes Database.csv

In [ ]:
train=pd.read_csv('/content/Pima-Indians-Diabetes-Database/Pima Indians Diabetes Database.csv', index_col=False)

# Preprocessing

## Analyzing

In [56]:
# credit: https://www.kaggle.com/willkoehrsen/start-here-a-gentle-introduction. 

def missing_values_table(df):
        # Total missing values
        mis_val = df.isnull().sum()
        
        # Percentage of missing values
        mis_val_percent = 100 * df.isnull().sum() / len(df)
        
        # Make a table with the results
        mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)
        
        # Rename the columns
        mis_val_table_ren_columns = mis_val_table.rename(
        columns = {0 : 'Missing Values', 1 : '% of Total Values'})
        
        # Sort the table by percentage of missing descending
        mis_val_table_ren_columns = mis_val_table_ren_columns[
            mis_val_table_ren_columns.iloc[:,1] != 0].sort_values(
        '% of Total Values', ascending=False).round(1)
        
        # Print some summary information
        print ("Your selected dataframe has " + str(df.shape[1]) + " columns.\n"      
            "There are " + str(mis_val_table_ren_columns.shape[0]) +
              " columns that have missing values.")
        
        # Return the dataframe with missing information
        return mis_val_table_ren_columns

In [57]:
train.head()

   Number of times pregnant  ...  Class variable (0 or 1)
0                         6  ...                        1
1                         1  ...                        0
2                         8  ...                        1
3                         1  ...                        0
4                         0  ...                        1

[5 rows x 9 columns]

In [58]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                                                                    Non-Null Count  Dtype
---  ------                                                                    --------------  -----
 0   Number of times pregnant                                                  768 non-null    int64
 1   Plasma glucose concentration a 2 hours in an oral glucose tolerance test  763 non-null    float64
 2   Diastolic blood pressure (mm Hg)                                          733 non-null    float64
 3   Triceps skin fold thickness (mm)                                          541 non-null    float64
 4   2-Hour serum insulin (mu U/ml)                                            394 non-null    float64
 5   Body mass index (weight in kg/(height in m)^2)                            757 non-null    float64
 6   Diabetes pedigree function                                                768 non-null    float64
 7   Age (years)                                                               768 non-null    int64
 8   Class variable (0 or 1)                                                   768 non-null    int64
dtypes: float64(6), int64(3)
memory usage: 54.1 KB

In [59]:
train.isnull().sum()

Number of times pregnant                                                      0
Plasma glucose concentration a 2 hours in an oral glucose tolerance test      5
Diastolic blood pressure (mm Hg)                                             35
Triceps skin fold thickness (mm)                                            227
2-Hour serum insulin (mu U/ml)                                              374
Body mass index (weight in kg/(height in m)^2)                               11
Diabetes pedigree function                                                    0
Age (years)                                                                   0
Class variable (0 or 1)                                                       0
dtype: int64

In [60]:
train.describe()

       Number of times pregnant  ...  Class variable (0 or 1)
count                768.000000  ...               768.000000
mean                   3.845052  ...                 0.348958
std                    3.369578  ...                 0.476951
min                    0.000000  ...                 0.000000
25%                    1.000000  ...                 0.000000
50%                    3.000000  ...                 0.000000
75%                    6.000000  ...                 1.000000
max                   17.000000  ...                 1.000000

[8 rows x 9 columns]

Although there is no missing Value in a sense that there is no Nan Value we can cleraly see that here 0 represent missing value in most categories. So we will need to change these 0 to Nan so we can see the amount of missing value more easily.

In [61]:
cols = ['Plasma glucose concentration a 2 hours in an oral glucose tolerance test', 'Diastolic blood pressure (mm Hg)', 'Triceps skin fold thickness (mm)', 
     '2-Hour serum insulin (mu U/ml)', 'Body mass index (weight in kg/(height in m)^2)', 'Diabetes pedigree function', 
     'Age (years)']
train[cols] = train[cols].replace(0,np.nan)

In [62]:
missing_values_table(train)

Your selected dataframe has 9 columns.
There are 5 columns that have missing values.

                                                    Missing Values  % of Total Values
2-Hour serum insulin (mu U/ml)                                 374               48.7
Triceps skin fold thickness (mm)                               227               29.6
Diastolic blood pressure (mm Hg)                                35                4.6
Body mass index (weight in kg/(height in m)^2)                  11                1.4
Plasma glucose concentration a 2 hours in an or...               5                0.7

In [63]:
train["2-Hour serum insulin (mu U/ml)"].unique()

array([ nan,  94., 168.,  88., 543., 846., 175., 230.,  83.,  96., 235.,
       146., 115., 140., 110., 245.,  54., 192., 207.,  70., 240.,  82.,
        36.,  23., 300., 342., 304., 142., 128.,  38., 100.,  90., 270.,
        71., 125., 176.,  48.,  64., 228.,  76., 220.,  40., 152.,  18.,
       135., 495.,  37.,  51.,  99., 145., 225.,  49.,  50.,  92., 325.,
        63., 284., 119., 204., 155., 485.,  53., 114., 105., 285., 156.,
        78., 130.,  55.,  58., 160., 210., 318.,  44., 190., 280.,  87.,
       271., 129., 120., 478.,  56.,  32., 744., 370.,  45., 194., 680.,
       402., 258., 375., 150.,  67.,  57., 116., 278., 122., 545.,  75.,
        74., 182., 360., 215., 184.,  42., 132., 148., 180., 205.,  85.,
       231.,  29.,  68.,  52., 255., 171.,  73., 108.,  43., 167., 249.,
       293.,  66., 465.,  89., 158.,  84.,  72.,  59.,  81., 196., 415.,
       275., 165., 579., 310.,  61., 474., 170., 277.,  60.,  14.,  95.,
       237., 191., 328., 250., 480., 265., 193.,  79.,  86., 326., 188.,
       106.,  65., 166., 274.,  77., 126., 330., 600., 185.,  25.,  41.,
       272., 321., 144.,  15., 183.,  91.,  46., 440., 159., 540., 200.,
       335., 387.,  22., 291., 392., 178., 127., 510.,  16., 112.])

# Treat Missings Values

## Deleting Rows / Listwise Deletion

Delete all row with missing values

In [64]:
# train_test
# train_deleting_r_age = train_new.copy()
# train_deleting_r_age.dropna(subset=['Age'],how='any',inplace=True)
# train_deleting_r_age['Age'].isnull().sum()

train_delete_row = train.copy()
train_delete_row.dropna(inplace=True)
train_delete_row.isnull().sum()

Number of times pregnant                                                    0
Plasma glucose concentration a 2 hours in an oral glucose tolerance test    0
Diastolic blood pressure (mm Hg)                                            0
Triceps skin fold thickness (mm)                                            0
2-Hour serum insulin (mu U/ml)                                              0
Body mass index (weight in kg/(height in m)^2)                              0
Diabetes pedigree function                                                  0
Age (years)                                                                 0
Class variable (0 or 1)                                                     0
dtype: int64

In [65]:

train_delete_row.to_csv('Pima-Indians-Diabetes-Database/deletedRows.csv', index=False)
train_delete_row

     Number of times pregnant  ...  Class variable (0 or 1)
3                           1  ...                        0
4                           0  ...                        1
6                           3  ...                        1
8                           2  ...                        1
13                          1  ...                        1
..                        ...  ...                      ...
753                         0  ...                        1
755                         1  ...                        1
760                         2  ...                        0
763                        10  ...                        0
765                         5  ...                        0

[392 rows x 9 columns]

## Replacing With Mean

In [66]:
def filter1(dataset):
    for col in dataset.columns:
        #print(dataset[col].dtypes)
        dataset[col].fillna(dataset[col].mean(),inplace=True)            

    return dataset

In [67]:
train_mean = train.copy()

train_mean = filter1(train_mean)
train_mean

     Number of times pregnant  ...  Class variable (0 or 1)
0                           6  ...                        1
1                           1  ...                        0
2                           8  ...                        1
3                           1  ...                        0
4                           0  ...                        1
..                        ...  ...                      ...
763                        10  ...                        0
764                         2  ...                        0
765                         5  ...                        0
766                         1  ...                        1
767                         1  ...                        0

[768 rows x 9 columns]

In [68]:
missing_values_table(train_mean)

Your selected dataframe has 9 columns.
There are 0 columns that have missing values.

Empty DataFrame
Columns: [Missing Values, % of Total Values]
Index: []

In [69]:
train_mean.to_csv('Pima-Indians-Diabetes-Database/mean.csv', index=False)
train_mean

     Number of times pregnant  ...  Class variable (0 or 1)
0                           6  ...                        1
1                           1  ...                        0
2                           8  ...                        1
3                           1  ...                        0
4                           0  ...                        1
..                        ...  ...                      ...
763                        10  ...                        0
764                         2  ...                        0
765                         5  ...                        0
766                         1  ...                        1
767                         1  ...                        0

[768 rows x 9 columns]

## Assigning An Unique Category

In [70]:
train_unique_categ = train.copy()
missing_values_table(train_unique_categ)

Your selected dataframe has 9 columns.
There are 5 columns that have missing values.

                                                    Missing Values  % of Total Values
2-Hour serum insulin (mu U/ml)                                 374               48.7
Triceps skin fold thickness (mm)                               227               29.6
Diastolic blood pressure (mm Hg)                                35                4.6
Body mass index (weight in kg/(height in m)^2)                  11                1.4
Plasma glucose concentration a 2 hours in an or...               5                0.7

In [71]:
train_unique_categ["2-Hour serum insulin (mu U/ml)"].describe()

count    394.000000
mean     155.548223
std      118.775855
min       14.000000
25%       76.250000
50%      125.000000
75%      190.000000
max      846.000000
Name: 2-Hour serum insulin (mu U/ml), dtype: float64

In [72]:
cat = "2-Hour serum insulin (mu U/ml)"
train_unique_categ[cat] = train_unique_categ.replace(np.nan,-1)

train_unique_categ.loc[ train_unique_categ[cat] < 0, cat] = 0
train_unique_categ.loc[(train_unique_categ[cat] >= 0) & (train_unique_categ[cat] <= 76.25), cat] = 1
train_unique_categ.loc[(train_unique_categ[cat] > 76.25) & (train_unique_categ[cat] <= 125), cat] = 2
train_unique_categ.loc[(train_unique_categ[cat] > 125) & (train_unique_categ[cat] <= 190), cat] = 3
train_unique_categ.loc[(train_unique_categ[cat] > 190) & (train_unique_categ[cat] <= 900), cat] = 4

In [73]:
cat = "Triceps skin fold thickness (mm)"

train_unique_categ[cat].describe()

count    541.000000
mean      29.153420
std       10.476982
min        7.000000
25%       22.000000
50%       29.000000
75%       36.000000
max       99.000000
Name: Triceps skin fold thickness (mm), dtype: float64

In [74]:
train_unique_categ[cat] = train_unique_categ.replace(np.nan,-1)

train_unique_categ.loc[ train_unique_categ[cat] < 0, cat] = 0
train_unique_categ.loc[(train_unique_categ[cat] > 0) & (train_unique_categ[cat] <= 22), cat] = 1
train_unique_categ.loc[(train_unique_categ[cat] > 22) & (train_unique_categ[cat] <= 29), cat] = 2
train_unique_categ.loc[(train_unique_categ[cat] > 29) & (train_unique_categ[cat] <= 36), cat] = 3
train_unique_categ.loc[(train_unique_categ[cat] > 36) & (train_unique_categ[cat] <= 100), cat] = 4

In [75]:
cat = "Diastolic blood pressure (mm Hg)"

train_unique_categ[cat].describe()

count    733.000000
mean      72.405184
std       12.382158
min       24.000000
25%       64.000000
50%       72.000000
75%       80.000000
max      122.000000
Name: Diastolic blood pressure (mm Hg), dtype: float64

In [76]:
train_unique_categ[cat] = train_unique_categ.replace(np.nan,-1)

train_unique_categ.loc[ train_unique_categ[cat] < 0, cat] = 0
train_unique_categ.loc[(train_unique_categ[cat] > 0) & (train_unique_categ[cat] <= 64), cat] = 1
train_unique_categ.loc[(train_unique_categ[cat] > 64) & (train_unique_categ[cat] <= 72), cat] = 2
train_unique_categ.loc[(train_unique_categ[cat] > 72) & (train_unique_categ[cat] <= 80), cat] = 3
train_unique_categ.loc[(train_unique_categ[cat] > 80) & (train_unique_categ[cat] <= 122), cat] = 4

In [77]:
cat = "Body mass index (weight in kg/(height in m)^2)"

train_unique_categ[cat].describe()

count    757.000000
mean      32.457464
std        6.924988
min       18.200000
25%       27.500000
50%       32.300000
75%       36.600000
max       67.100000
Name: Body mass index (weight in kg/(height in m)^2), dtype: float64

In [78]:
train_unique_categ[cat] = train_unique_categ.replace(np.nan,-1)

train_unique_categ.loc[ train_unique_categ[cat] < 0, cat] = 0
train_unique_categ.loc[(train_unique_categ[cat] > 0) & (train_unique_categ[cat] <= 27.5), cat] = 1
train_unique_categ.loc[(train_unique_categ[cat] > 27.5) & (train_unique_categ[cat] <= 32.3), cat] = 2
train_unique_categ.loc[(train_unique_categ[cat] > 32.3) & (train_unique_categ[cat] <= 36.6), cat] = 3
train_unique_categ.loc[(train_unique_categ[cat] > 36.6) & (train_unique_categ[cat] <= 67.1), cat] = 4

In [79]:
cat = "Plasma glucose concentration a 2 hours in an oral glucose tolerance test"

train_unique_categ[cat].describe()

count    763.000000
mean     121.686763
std       30.535641
min       44.000000
25%       99.000000
50%      117.000000
75%      141.000000
max      199.000000
Name: Plasma glucose concentration a 2 hours in an oral glucose tolerance test, dtype: float64

In [80]:
train_unique_categ[cat] = train_unique_categ.replace(np.nan,-1)

train_unique_categ.loc[ train_unique_categ[cat] < 0, cat] = 0
train_unique_categ.loc[(train_unique_categ[cat] > 0) & (train_unique_categ[cat] <= 99), cat] = 1
train_unique_categ.loc[(train_unique_categ[cat] > 99) & (train_unique_categ[cat] <= 117), cat] = 2
train_unique_categ.loc[(train_unique_categ[cat] > 117) & (train_unique_categ[cat] <= 141), cat] = 3
train_unique_categ.loc[(train_unique_categ[cat] > 141) & (train_unique_categ[cat] <= 199), cat] = 4

In [81]:
train_unique_categ.to_csv('Pima-Indians-Diabetes-Database/uniqueCategory.csv', index=False)
train_unique_categ

     Number of times pregnant  ...  Class variable (0 or 1)
0                           6  ...                        1
1                           1  ...                        0
2                           8  ...                        1
3                           1  ...                        0
4                           0  ...                        1
..                        ...  ...                      ...
763                        10  ...                        0
764                         2  ...                        0
765                         5  ...                        0
766                         1  ...                        1
767                         1  ...                        0

[768 rows x 9 columns]

## Using Algorithms Which Support Missing Values | KNN Imputer 5 nearest neighbours

In [82]:
train_knn = train.copy()

In [83]:
missing_values_table(train_knn)

Your selected dataframe has 9 columns.
There are 5 columns that have missing values.

                                                    Missing Values  % of Total Values
2-Hour serum insulin (mu U/ml)                                 374               48.7
Triceps skin fold thickness (mm)                               227               29.6
Diastolic blood pressure (mm Hg)                                35                4.6
Body mass index (weight in kg/(height in m)^2)                  11                1.4
Plasma glucose concentration a 2 hours in an or...               5                0.7

In [84]:
train_knn

     Number of times pregnant  ...  Class variable (0 or 1)
0                           6  ...                        1
1                           1  ...                        0
2                           8  ...                        1
3                           1  ...                        0
4                           0  ...                        1
..                        ...  ...                      ...
763                        10  ...                        0
764                         2  ...                        0
765                         5  ...                        0
766                         1  ...                        1
767                         1  ...                        0

[768 rows x 9 columns]

In [85]:

from sklearn.impute import KNNImputer
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
train_knn = pd.DataFrame(scaler.fit_transform(train_knn), columns = train_knn.columns)
train_knn

     Number of times pregnant  ...  Class variable (0 or 1)
0                    0.352941  ...                      1.0
1                    0.058824  ...                      0.0
2                    0.470588  ...                      1.0
3                    0.058824  ...                      0.0
4                    0.000000  ...                      1.0
..                        ...  ...                      ...
763                  0.588235  ...                      0.0
764                  0.117647  ...                      0.0
765                  0.294118  ...                      0.0
766                  0.058824  ...                      1.0
767                  0.058824  ...                      0.0

[768 rows x 9 columns]

In [86]:
imputer = KNNImputer(n_neighbors=5)
train_knn = pd.DataFrame(imputer.fit_transform(train_knn),columns = train_knn.columns)
train_knn

     Number of times pregnant  ...  Class variable (0 or 1)
0                    0.352941  ...                      1.0
1                    0.058824  ...                      0.0
2                    0.470588  ...                      1.0
3                    0.058824  ...                      0.0
4                    0.000000  ...                      1.0
..                        ...  ...                      ...
763                  0.588235  ...                      0.0
764                  0.117647  ...                      0.0
765                  0.294118  ...                      0.0
766                  0.058824  ...                      1.0
767                  0.058824  ...                      0.0

[768 rows x 9 columns]

In [87]:
train_knn.isna().any()
train_knn

     Number of times pregnant  ...  Class variable (0 or 1)
0                    0.352941  ...                      1.0
1                    0.058824  ...                      0.0
2                    0.470588  ...                      1.0
3                    0.058824  ...                      0.0
4                    0.000000  ...                      1.0
..                        ...  ...                      ...
763                  0.588235  ...                      0.0
764                  0.117647  ...                      0.0
765                  0.294118  ...                      0.0
766                  0.058824  ...                      1.0
767                  0.058824  ...                      0.0

[768 rows x 9 columns]

In [88]:
train_knn.to_csv('Pima-Indians-Diabetes-Database/knn.csv', index=False)
train_knn

     Number of times pregnant  ...  Class variable (0 or 1)
0                    0.352941  ...                      1.0
1                    0.058824  ...                      0.0
2                    0.470588  ...                      1.0
3                    0.058824  ...                      0.0
4                    0.000000  ...                      1.0
..                        ...  ...                      ...
763                  0.588235  ...                      0.0
764                  0.117647  ...                      0.0
765                  0.294118  ...                      0.0
766                  0.058824  ...                      1.0
767                  0.058824  ...                      0.0

[768 rows x 9 columns]

# Accuracy

In [118]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

def model(train):
  values = train.values
  X = values[:,0:8]
  y = values[:,8]
  model = LinearDiscriminantAnalysis()
  kfold = KFold(n_splits=6)
  result = cross_val_score(model, X, y, cv=kfold, scoring = 'accuracy')
  print(result.mean())

In [108]:
train_delete_row.shape

(392, 9)

In [119]:
# Logistic Regression :
print("logistic Regression: Replacing With Mean")

model(train_mean)
print("logistic Regression: Deleting Rows")
model(train_delete_row)
print("logistic Regression: Unique Category")
model(train_unique_categ)
print("logistic Regression: KNN")
model(train_knn)

logistic Regression: Replacing With Mean
0.7669270833333334
logistic Regression: Deleting Rows
0.7832944832944834
logistic Regression: Unique Category
0.6588541666666666
logistic Regression: KNN
0.7747395833333334